logging:
  level:
    root: INFO
    '[com.template.base]': DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{requestId:-}] %logger{36} - %msg%n"

management:
  tracing:
    sampling:
      probability: 1.0
